title: 2023 Olomouc winter school on AI & society
description: An intensive course with lectures on the history of AI, technology and society, science fiction and pop culture, current applications of AI, and practical exercises on making sense of the complex discourses on technology.
theme: minima