title: 2023 Olomouc winter school on AI and society
description: An intensive course with lectures on the history of AI, technology and society, science fiction and pop culture, current applications of AI, and practical exercises on making sense of the complex discourses on technology.
theme: jekyll-theme-minimal
show_downloads: false
nav: true
owner: true
owner_name: Auli Viidalepp
owner_url: https://auli.viidalepp.org